proof/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    #url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html')),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^login/', views.user_login, name='login'),
    url(r'^logout/', views.user_logout, name='logout'),
    # url(r'^dashboard/', views.dashboard, name='dashboard'),
    # url(r'^signup/$', core_views.signup, name='register'),

]

proof/projects/urls.py
from django.conf.urls import url
from . import views

app_name = 'projects'

urlpatterns = [
    url(r'^detail/(?P<id>\d+)/$', views.projectDetailView, name='detail'),
]

proof/proof/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts.views import user_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', user_login, name='login'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^projects/', include('projects.urls')),
]

proof/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)
    picture = models.ImageField(upload_to='profile_pics', blank=True, null=True)
    #position = models.CharField(max_length=100)

    def __str__(self):
        return self.username

proof/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    #password = forms.CharField(widget=forms.PasswordInput())
    first_name = forms.CharField(label='First Name', required=True)
    last_name = forms.CharField(label='Last Name', required=True)
    email = forms.EmailField(max_length=200, required=True)

    class Meta():
        model = User
        fields = ('first_name','last_name','email', 'is_staff')
        exclude = ('password',)

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model= UserProfileInfo
        fields = ('picture',)

proof/accounts/views.py

#django
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, render_to_response, get_object_or_404
from django.urls import reverse, reverse_lazy

#local
from .forms import UserProfileInfoForm, UserForm
from projects.models import Project, Task, TeamRecord
# Create your views here.

def register(request):
    if request.method == 'POST':
        #get data from request
        form = UserCreationForm(request.POST)
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')

        # save user form
        user = user_form.save(commit=False)
        # first use first_name and last_name to create nickname
        username='{}{}'.format(first_name, last_name)
        user.username = username
        user.password = 'testpassword'
        user.email = user.email.lower()
        #check if new user does not duplicate either username nor email
        if User.objects.filter(username=username).exists():
            return render(request, 'accounts/register.html',{
            'messages':'User with the same First and Last Name already exists in database. You can not duplicate user.',
            'user_form':user_form,
            'profile_form':profile_form})
        if User.objects.filter(email=user.email).exists():
            return render(request, 'accounts/register.html',{
            'messages':'User with the same email already exists in database. Email have to be unique.',
            'user_form':user_form,
            'profile_form':profile_form})

        user.set_password(user.password)
        user.save()

        #save user profile form
        profile = profile_form.save(commit=False)
        profile.user = user

        #check if profile picture is ready to be saved
        if 'profile_pic' in request.FILES:
            profile.profile_pic = request.FILES['profile_pic']
            profile.save()
        else:
            print(user_form.errors, profile_form.errors)

        messages = 'New User: {} was created.'.format(user.username)
        return render(request, 'accounts/login.html',{'messages':messages})
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
        return render(request, 'accounts/register.html',{'user_form':user_form,
                                        'profile_form':profile_form})


def user_login(request):
    if request.method == 'POST':
        #print('login details are analyst')
        email = request.POST.get('email')
        password = request.POST.get('password')
        if User.objects.filter(email=email).exists():
            username = get_object_or_404(User, email=email).username
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    # log in with passwod
                    login(request, user)
                    messages = 'You are logged in as: {}.'.format(user.username)
                    return redirect('accounts:profile')
                else:
                    #user not active
                    return render(request, 'accounts/login.html',{'messages':'User is not active.'})
            else:
                # wrong password or username
                return render(request, 'accounts/login.html',{'messages':'invalid login details.'})
        else:
            return render(request, 'accounts/login.html',{'messages':'Email does NOT exists in database.'})
    else:
        # GET
        return render(request, 'accounts/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('accounts:login'))

@login_required
def profile(request):
    if request.user.is_authenticated():
        # GENERTE CONTEXT DATA FOR STAFF AND NORAL USERS
        tasks = Task.objects.filter(master=request.user)
        #Get user projects and remove duplicates
        my_projects = TeamRecord.objects.filter(member=request.user).distinct()
        project_list = []
        if my_projects.count() >=1:
            for i in my_projects:
                append_flag = True
                for item in project_list:
                    if i.project.id == item.id:
                        append_flag = False
                if append_flag==True:
                    project_list.append(i.project)
            my_projects = project_list

        # GENERATE ADDITIONAL DATA FOR STAFF
        if request.user.is_staff:
            #generate context data for staff member
            all_users = User.objects.all()
            all_projects = Project.objects.all()
            context = {'user':request.user, 'tasks':tasks, 'my_projects':my_projects,'all_users': all_users, 'all_projects':all_projects}
        else:
            #generate context data for NON staff member

            context = {'user':request.user, 'tasks':tasks, 'my_projects':my_projects}

        return render(request,'accounts/profile.html',context)

    else:
        return redirect('accounts:login')

proof/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}

<h4>LogIn</h4>

{% if messages %}
  {{ messages }}
{% endif %}

<form class="" action='{% url 'accounts:login' %}'  method="POST">
  {% csrf_token %}
  <label for='email'>Email</label>
  <input type="text" name="email" placeholder="Enter Work Email">

  <label for='password'>Password</label>
  <input type="password" name="password" placeholder="Enter Password">

  <input type="submit" name="" value="submit">
</form>

{% endblock %}

proof/accounts/templates/accounts/profile.html
{% extends 'base.html' %}



{% block body %}
<h1>Profile Page</h1>

{% if user.is_authenticated %}<a href="{% url 'accounts:logout' %}">Logout</a>{% endif %}
{% if not user.is_authenticated %}<a href="{% url 'accounts:login' %}">Login</a>{% endif %}

{% if messages %}
  {{ messages }}
{% endif %}


  {% if user.is_staff %}
  <h3> Project Management </h3>

  <ul>
    {% for project in all_projects %}
    <li> <a href="{% url 'projects:detail' id=project.id %}">{{ project.title }} </a></li>
    {% endfor %}
  </ul>

  <h3> Employee Management </h3>
  <ul>
    {% for user in all_users %}
      <li>{{ user.first_name }} &nbsp {{ user.last_name }}</li>
    {% endfor %}
  </ul>

  <a href="{% url 'accounts:register' %}">Add User</a>
  <div class="">

  </div>
  {% endif %}

  <h3> Your Profile </h3>
  <p>Welcome: {{ user.first_name }} &nbsp {{ user.last_name }} </p>

  <h3> Your Projects </h3>
  <ul>
    {% for project in my_projects %}
      <li> <a href="{% url 'projects:detail' id=project.id %}">{{ project.title }} </a> </li>
    {% endfor %}
  </ul>
  <h3>Your Tasks</h3>
  <ul>
    {% for task in tasks %}
      <li> {{ task.title }} </li>
    {% endfor %}
  </ul>
  {{ tasks.title }}



{% endblock %}

proof/accounts/templates/accounts/register.html
{% extends 'base.html' %}




{% block body %}
  <!-- ERROR MESSSSAGES IF FOR WAS INCORECTLY FILLED -->
  {% if form.errors %}
      {% for field in form %}
          {% for error in field.errors %}
              <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
          </div>
      {% endfor %}
  {% endif %}
  {% if messages %}
    {{ messages }}
  {% endif %}


  <!-- REGISTRATION FORM -->
  <h2>registration page</h2>
  <form class="" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}